name: 

on:  
  push:  
    branches:  
      - main  
      - 'feature/*'  
  pull_request:  
    branches:  
      - main  

jobs:  
  build:  

    runs-on: ubuntu-latest  

    steps:  
      - name: Check out the repository  
        uses: actions/checkout@v2  
 
      - name: Set up Node.js  
        uses: actions/setup-node@v2  
        with:  
          node-version: '22.14.0' # Specify the Node.js version to match your project  

      - name: Cache Node modules  
        uses: actions/cache@v2  
        with:  
          path: ~/.npm  
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}  
          restore-keys: |  
            ${{ runner.os }}-npm-  

      - name: Install Angular CLI  
        run: npm install -g @angular/cli  

      - name: Install dependencies  
        run: npm install

      - name: Build the application  
        run: ng build 
      - name: Run Tests
        run: |
          if npm ls --depth=0 jest; then
            echo "Running Jest tests"
            npm run test -- --watch=false
          else
            echo "Running Karma tests"
            ng test --browsers=ChromeHeadless --code-coverage --watch=false
          fi

   

      # - name: Set up SonarQube Scanner
      #   uses: sonarsource/sonarcloud-github-action@v2
      #   with:
      #     sonar-token: ${{ secrets.SONAR_TOKEN }}  # Store your SonarQube token in GitHub Secrets
      #     sonar-project-key: "sample-angular-service"    # Set your SonarQube project key
      #     sonar-project-name: "sample-angular-service"  # Set your SonarQube project name

      # Run SonarQube Scan
      - name: Run SonarQube analysis
        run: |
          # Install SonarQube scanner
          npm install -g sonar-scanner

          # Run SonarQube analysis
          sonar-scanner \
            -Dsonar.projectKey="tipstat2405_sample-angular-service" \
            -Dsonar.projectName="sample-angular-service" \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization="tipstat2405" \
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
            -Dsonar.typescript.tsconfigPath=tsconfig.json
