name: CI  

on:  
  push:  
    branches:  
      - main  
      - 'feature/*'  
  pull_request:  
    branches:  
      - main  

jobs:  
  build:  

    runs-on: ubuntu-latest  

    steps:  
      - name: Check out the repository  
        uses: actions/checkout@v2  

      - name: Set up Node.js  
        uses: actions/setup-node@v2  
        with:  
          node-version: '22.14.0' # Specify the Node.js version to match your project  

      - name: Cache Node modules  
        uses: actions/cache@v2  
        with:  
          path: ~/.npm  
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}  
          restore-keys: |  
            ${{ runner.os }}-npm-  

      - name: Install Angular CLI  
        run: npm install -g @angular/cli  

      - name: Install dependencies  
        run: npm install

      - name: Build the application  
        run: ng build 
      - name: Run Tests
        run: |
          if npm ls --depth=0 jest; then
            echo "Running Jest tests"
            npm run test -- --watch=false
          else
            echo "Running Karma tests"
            npm run test
          fi

      - name: Run Jest tests  
        id: jest_test  
        run: |  
          if [ -f "jest.config.js" ]; then  
            echo "Running Jest tests..."  
            npm run test -- --ci  
          else  
            echo "No Jest configuration found, skipping Jest tests."  
            echo "::set-output name=jest_found::false"  
          fi  
        continue-on-error: true  

      - name: Run Karma tests  
        id: karma_test  
        run: |  
          if [ -f "karma.conf.js" ]; then  
            echo "Running Karma tests..."  
            npm run test -- --watch=false  
          else  
            echo "No Karma configuration found, skipping Karma tests."  
            echo "::set-output name=karma_found::false"  
          fi  
        continue-on-error: true  

      - name: Check for vulnerabilities  
        run: npm audit
